kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-zfspv-test-volume
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
