apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: openebs-zfspv-test-volume 
  containers:
    - name: task-pv-container
      image: busybox
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      volumeMounts:
        - mountPath: "/myvolume"
          name: task-pv-storage



